# Landon Beard
# Simple kubernetes deployment file that runs NGINX containers
# and exposes the service to 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tilt-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tilt-app
  template:
    metadata:
      labels:
        app: tilt-app
    spec:
      containers:
      - name: tilt-app
        image: nginx:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: tilt-app-service
spec:
  selector:
    app: tilt-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
  type: NodePort
